### ISSUE TITLE
Issues with certain usernames

### ISSUE THREAD

**Issue by trvrplk** [jakeledoux/live#1]
Previously the site worked fine for me, but starting yesterday it would only load my tile and none of my friends'. The console throws the follow error:

```
jquery-3.4.1.min.js:2 Uncaught Error: Syntax error, unrecognized expression: .user-tile[user=Mr.Pop-N-Fresh]
    at Function.se.error (jquery-3.4.1.min.js:2)
    at se.tokenize (jquery-3.4.1.min.js:2)
    at se.select (jquery-3.4.1.min.js:2)
    at Function.se [as find] (jquery-3.4.1.min.js:2)
    at k.fn.init.find (jquery-3.4.1.min.js:2)
    at new k.fn.init (jquery-3.4.1.min.js:2)
    at k (jquery-3.4.1.min.js:2)
    at createTile (friends.js?rev=a-cache-you-cant-sweat-out:29)
    at refreshLastFM (friends.js?rev=a-cache-you-cant-sweat-out:208)
    at friends.js?rev=a-cache-you-cant-sweat-out:227
```

So it seems that that user's name is causing the issue. I didn't follow them until the other day, which would explain why this never came up before. I think this would be a simple fix in the JavaScript.

There is, though, another issue that's probably worse for some users. I wanted to see what part of "Mr.Pop-N-Fresh" was causing the issue, so I tested by looking at the live page for some users I follow who have either a "." or a "-" in their username. I found that any user whose name contains a "-" causes a 404 error. I'm not entirely sure what the issue here is; I have [my own last.fm dashboard thing](https://github.com/trvrplk/lastdash), and when I look up the same users, it works fine. Since your site gives a 404 error, though, it doesn't output anything to the console.

(Also, in hindsight I realized it was the "." in "Mr.Pop-N-Fresh" that caused the issue, since I've followed users with "-" in their name for a while and it always worked fine.)

**Comment by trvrplk** [comment]
Okay, I opened a PR that might fix this

**Comment by jakeledoux** [comment]
Guess I didn't plan for usernames allowing such unorthodox characters. Those selectors should have been quoted regardless, I can only chalk it up to laziness.

I've just updated the server to include the hotfix. Should be working now.

**Comment by jakeledoux** [comment]
It's impossible for "Mr.Pop-N-Fresh" to use the site for the time being as the 404 is caused by a slightly less trivial server configuration issue. Feel free to create a second issue for that. Thanks for reporting this!

**Comment by jakeledoux** [comment]
One final comment: My hosting provider (DigitalOcean) seems to be suffering some intermittent outages at the moment. So if you have trouble loading the site - that's why.

**Comment by trvrplk** [comment]
Hah I did notice that. And no problem!
